#pragma once

enum MessageCode
{
	SIGN_UP_REQUEST,
	LOGIN_REQUEST,
	LOGOUT_REQUEST,
	CREATE_ROOM_REQUEST,
	GET_ROOMS_REQUEST,
	GET_PLAYERS_IN_ROOM_REQUEST,
	JOIN_ROOM_REQUEST,
	GET_STATISTICS_REQUEST,
	ERROR_RESPONSE,
	SIGN_UP_RESPONSE,
	LOGIN_RESPONSE
};